POST http://localhost:9090/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJleHAiOjE3NjAwNTQ0MDksInVzZXJJZCI6MX0.TGu14ilOCsifmnAH8XhkgRn6S8hCTXjfDXpNNf_UE_w

{
     "name": "Test event 1",
     "description": "A test event1",
     "location": "A test location",
     "dateTime": "2025-01-01T15:30:00.000Z"
}