DELETE  http://localhost:9090/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAZXhhbXBsZS5jb20iLCJleHAiOjE3NjAwNTQ0MDksInVzZXJJZCI6MX0.TGu14ilOCsifmnAH8XhkgRn6S8hCTXjfDXpNNf_UE_w
